### ISSUE TITLE
Emulated terminals have no internet

### ISSUE THREAD

**Issue by misfire** [Tyriar/pty.js#14]
the terminals themselves don't seem to have internet access, anyway around this or not possible?

Works fine using normal spawn, but I want unbuffered output so using pty.

[http://i.imgur.com/62MZPEt.png](http://i.imgur.com/62MZPEt.png)

**Comment by Tyriar** [comment]
I've never had any issues with this, how are you initializing the lib?

**Comment by misfire** [comment]
var pty = require('pty.js');

var term = pty.spawn('cmd.exe', [], {
  name: 'xterm-color',
  cols: 80,
  rows: 30,
  cwd: process.env.HOME,
  env: process.env
});

term.on('data', function(data) {
  console.log(data);
});


term.write(process.cwd() + "\\miners\\eth\\claymore\\EthDcrMiner64.exe" + '\r');
term.resize(100, 40);

**Comment by Tyriar** [comment]
This seems to work fine for me:

```js
var pty = require('.');

var term = pty.spawn('cmd.exe', [], {
name: 'xterm-color',
cols: 80,
rows: 30,
cwd: process.env.HOME,
env: process.env
});

term.on('data', function(data) {
console.log(data);
});

term.write('ping google.com -t\r\n');
```

Output:

```
C:\Users\Daniel\Documents\dev\Tyriar\pty.js>node test.js
Microsoft Windows [Version 10.0.14931]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Daniel>
C:\Users\Daniel>ping google.com -t

Pinging google.com [2607:f8b0:400a:800::200e] with 32 bytes of data:
Reply from 2607:f8b0:400a:800::200e: time=10ms

Reply from 2607:f8b0:400a:800::200e: time=10ms

Reply from 2607:f8b0:400a:800::200e: time=11ms

^C
```

**Comment by Tyriar** [comment]
Closing this off as it seems to work fine with minimal code snippet, probably environment related.
